name       : python-coverage
version    : 4.5.4
release    : 5
source     :
    - https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz : e07d9f1a23e9e93ab5c62902833bf3e4b1f65502927379148b6622686223125c
license    : Apache-2.0
component  : programming.python
summary    : Code coverage measurement and testing for Python
description: |
    Coverage.py is a Python module that measures code coverage during Python execution. It uses the code analysis tools and tracing hooks provided in the Python standard library to determine which lines are executable, and which have been executed.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

    pushd $installdir/usr/bin
        rm coverage{,2,3}
        ln -s $(basename coverage-2.*) coverage
        ln -s $(basename coverage-2.*) coverage2
        ln -s $(basename coverage-3.*) coverage3
    popd
