name       : python-coverage
version    : '5.4'
release    : 11
source     :
    - https://pypi.io/packages/source/c/coverage/coverage-5.4.tar.gz : 6d2e262e5e8da6fa56e774fb8e2643417351427604c2b177f8e8c5f75fc928ca
license    : Apache-2.0
component  : programming.python
summary    : Code coverage measurement and testing for Python
description: |
    Coverage.py is a Python module that measures code coverage during Python execution. It uses the code analysis tools and tracing hooks provided in the Python standard library to determine which lines are executable, and which have been executed.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
