name       : python-coverage
version    : 7.3.1
release    : 12
source     :
    - https://pypi.io/packages/source/c/coverage/coverage-7.3.1.tar.gz : 6cb7fe1581deb67b782c153136541e20901aa312ceedaf1467dcb35255787952
homepage   : https://github.com/nedbat/coveragepy
license    : Apache-2.0
component  : programming.python
summary    : Code coverage measurement and testing for Python
description: |
    Coverage.py is a Python module that measures code coverage during Python execution. It uses the code analysis tools and tracing hooks provided in the Python standard library to determine which lines are executable, and which have been executed.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
