name       : python-coverage
version    : 5.3.1
release    : 7
source     :
    - https://files.pythonhosted.org/packages/40/05/2c1d1405edeec38114abcd404f15a35a41029b89d0514aa8ad11ffcbde81/coverage-5.3.1.tar.gz : 38f16b1317b8dd82df67ed5daa5f5e7c959e46579840d77a67a4ceb9cef0a50b
license    : Apache-2.0
component  : programming.python
summary    : Code coverage measurement and testing for Python
description: |
    Coverage.py is a Python module that measures code coverage during Python execution. It uses the code analysis tools and tracing hooks provided in the Python standard library to determine which lines are executable, and which have been executed.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

    pushd $installdir/usr/bin
        rm coverage{,2,3}
        ln -s $(basename coverage-2.*) coverage
        ln -s $(basename coverage-2.*) coverage2
        ln -s $(basename coverage-3.*) coverage3
    popd
